const KEY='laxman-os-v2';
const $=s=>document.querySelector(s);
const today=()=>new Date().toISOString().slice(0,10);
const defaults={objective:'',tasks:[{text:'Choose one outcome that matters today',done:false}],projects:[],journal:'',money:'—',content:0,streak:0,lastDay:today(),completedDays:0,notes:[]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||JSON.parse(localStorage.getItem('laxman-os-v1')||'null')||defaults;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function syncDay(){const d=today();if(state.lastDay!==d){if(state.tasks.some(t=>t.done))state.streak=(state.streak||0)+1;state.tasks=state.tasks.filter(t=>!t.done);state.lastDay=d;state.completedDays=(state.completedDays||0)+1;save()}}
function render(){syncDay();$('#objective').value=state.objective||'';$('#journal').value=state.journal||'';$('#moneyValue').textContent=state.money||'—';$('#contentValue').textContent=state.content||0;$('#streakValue').textContent=state.streak||0;
 const list=$('#taskList');list.innerHTML='';state.tasks.forEach((t,i)=>{const el=document.createElement('div');el.className='task '+(t.done?'done':'');el.innerHTML=`<input type="checkbox" ${t.done?'checked':''}><span>${escapeHtml(t.text)}</span><button class="delete" aria-label="Delete task">×</button>`;el.querySelector('input').onchange=e=>{t.done=e.target.checked;save();render()};el.querySelector('.delete').onclick=()=>{state.tasks.splice(i,1);save();render()};list.appendChild(el)});
 const pl=$('#projectList');pl.innerHTML='';state.projects.forEach((p,i)=>{const el=document.createElement('div');el.className='project';el.innerHTML=`<span>●</span><b>${escapeHtml(p.name||p)}</b><small>${p.status||'active'}</small><button class="remove" aria-label="Remove project">×</button>`;el.querySelector('.remove').onclick=()=>{state.projects.splice(i,1);save();render()};pl.appendChild(el)});
 $('#taskCount').textContent=state.tasks.length;$('#doneCount').textContent=state.tasks.filter(x=>x.done).length;$('#projectCount').textContent=state.projects.length;updateScore();
}
function updateScore(){const total=state.tasks.length||1,done=state.tasks.filter(x=>x.done).length,objective=state.objective.trim()?20:0;$('#focusScore').textContent=Math.min(100,Math.round(done/total*80)+objective)}
function addTask(){const text=prompt('Task for today');if(text?.trim()){state.tasks.push({text:text.trim(),done:false});save();render()}}
function addProject(){if(state.projects.length>=3){alert('Focus limit reached. Finish, pause, or remove an active project before adding another.');return}const p=prompt('Active project');if(p?.trim()){state.projects.push({name:p.trim(),status:'active'});save();render()}}
function review(){const unfinished=state.tasks.filter(x=>!x.done).length,projects=state.projects.length;let title='Protect the focus.',msg='Your system is under control. Finish before expanding.';if(!state.objective.trim()){title='You have no defined target.';msg='Set one main objective. Without a target, a long task list becomes busywork.'}else if(projects>=3&&unfinished>2){title='You are overloaded.';msg=`${projects} active projects and ${unfinished} unfinished tasks. Starting another project would be avoidance, not progress.`}else if(projects>=3){title='Do not add another project.';msg='Three active projects is your ceiling. Finish one before starting anything new.'}else if(unfinished>3){title='Too many open loops.';msg=`${unfinished} tasks remain. Finish the task with the highest real-world consequence first.`}else if(unfinished===0){title='Execution complete.';msg='Everything planned is done. Stop inventing work and recover.'}$('#aiTitle').textContent=title;$('#aiMessage').textContent=msg}
$('#objective').oninput=e=>{state.objective=e.target.value;save();updateScore()};$('#journal').oninput=e=>{state.journal=e.target.value;save()};$('#clearObjective').onclick=()=>{state.objective='';save();render()};$('#addTask').onclick=addTask;$('#addProject').onclick=addProject;$('#reviewBtn').onclick=review;$('#saveJournal').onclick=()=>{const n=$('#journal').value.trim();if(n){state.notes.unshift({text:n,date:new Date().toLocaleString()});state.notes=state.notes.slice(0,30)}save();alert('Saved locally on this device.')};$('#clearData').onclick=()=>{if(confirm('Delete all local Laxman OS data?')){localStorage.removeItem(KEY);localStorage.removeItem('laxman-os-v1');location.reload()}};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('laxman-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('laxman-theme')==='dark')document.body.classList.add('dark');
const h=new Date().getHours();$('#greeting').textContent=h<12?'GOOD MORNING':h<18?'GOOD AFTERNOON':'GOOD EVENING';$('#dateText').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date());
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));render();