const KEY='laxman-os-v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{objective:'',tasks:[{text:'Choose one outcome that matters today',done:false}],projects:[],journal:'',money:'—',content:0,streak:0};
const $=s=>document.querySelector(s); const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function render(){ $('#objective').value=state.objective;$('#journal').value=state.journal;$('#moneyValue').textContent=state.money;$('#contentValue').textContent=state.content;$('#streakValue').textContent=state.streak;
 const list=$('#taskList');list.innerHTML='';state.tasks.forEach((t,i)=>{const el=document.createElement('div');el.className='task '+(t.done?'done':'');el.innerHTML=`<input type="checkbox" ${t.done?'checked':''}><span>${escapeHtml(t.text)}</span><button class="delete">×</button>`;el.querySelector('input').onchange=e=>{t.done=e.target.checked;save();render()};el.querySelector('.delete').onclick=()=>{state.tasks.splice(i,1);save();render()};list.appendChild(el)});
 const pl=$('#projectList');pl.innerHTML='';state.projects.forEach((p,i)=>{const el=document.createElement('div');el.className='project';el.innerHTML=`<span>●</span><b>${escapeHtml(p)}</b><small>active</small><button class="remove">×</button>`;el.querySelector('.remove').onclick=()=>{state.projects.splice(i,1);save();render()};pl.appendChild(el)});
 $('#taskCount').textContent=state.tasks.length;$('#doneCount').textContent=state.tasks.filter(x=>x.done).length;$('#projectCount').textContent=state.projects.length;updateScore();
}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function updateScore(){const total=state.tasks.length||1,done=state.tasks.filter(x=>x.done).length;$('#focusScore').textContent=Math.round(done/total*100);}
function addTask(){const text=prompt('Task for today');if(text?.trim()){state.tasks.push({text:text.trim(),done:false});save();render()}}
function addProject(){if(state.projects.length>=3){alert('Focus limit reached. Finish, pause, or remove an active project before adding another.');return}const p=prompt('Active project');if(p?.trim()){state.projects.push(p.trim());save();render()}}
function review(){const unfinished=state.tasks.filter(x=>!x.done).length;const projects=state.projects.length;let title='Good. Now protect the focus.';let msg='Your dashboard is under control. Finish before expanding.';if(projects>=3&&unfinished>2){title='You are overloaded.';msg=`You have ${projects} active projects and ${unfinished} unfinished tasks. Starting another project would be avoidance, not progress.`}else if(projects>=3){title='Do not add another project.';msg='Three active projects is your ceiling. Finish one before starting anything new.'}else if(unfinished>3){title='Too many open loops.';msg=`${unfinished} tasks are unfinished. Pick the one with the highest real-world consequence and finish it first.`}else if(unfinished===0){title='Execution complete.';msg='Everything planned for today is done. Stop inventing work and recover.'}$('#aiTitle').textContent=title;$('#aiMessage').textContent=msg}
$('#objective').oninput=e=>{state.objective=e.target.value;save()};$('#journal').oninput=e=>{state.journal=e.target.value;save()};$('#clearObjective').onclick=()=>{state.objective='';save();render()};$('#addTask').onclick=addTask;$('#addProject').onclick=addProject;$('#reviewBtn').onclick=review;$('#saveJournal').onclick=()=>{save();alert('Saved locally on this device.')};$('#clearData').onclick=()=>{if(confirm('Delete all local Laxman OS data?')){localStorage.removeItem(KEY);location.reload()}};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('laxman-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('laxman-theme')==='dark')document.body.classList.add('dark');
const h=new Date().getHours();$('#greeting').textContent=h<12?'GOOD MORNING':h<18?'GOOD AFTERNOON':'GOOD EVENING';$('#dateText').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date());
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));render();
