(()=>{
'use strict';
const BASE='https://apps.laxmannepal.com.np/Nepali-Patro/';
const signs=[['♈','मेष','ऊर्जा र पहल'],['♉','वृष','स्थिरता र व्यवहारिकता'],['♊','मिथुन','सम्पर्क र सिकाइ'],['♋','कर्कट','परिवार र भावना'],['♌','सिंह','आत्मविश्वास र नेतृत्व'],['♍','कन्या','योजना र विवरण'],['♎','तुला','सम्बन्ध र सन्तुलन'],['♏','वृश्चिक','एकाग्रता र परिवर्तन'],['♐','धनु','यात्रा र विस्तार'],['♑','मकर','अनुशासन र उपलब्धि'],['♒','कुम्भ','नयाँ विचार र स्वतन्त्रता'],['♓','मीन','सिर्जनशीलता र संवेदनशीलता']];
const p={overall:['आज प्राथमिकता स्पष्ट राख्दा काम सजिलै अघि बढ्नेछ।','आज धैर्य राखेर अघि बढ्नु लाभदायक हुनेछ।','सानो अवसरलाई व्यवस्थित रूपमा प्रयोग गर्दा राम्रो परिणाम आउन सक्छ।','आज नयाँ विचारलाई व्यवहारिक योजनामा बदल्ने राम्रो समय हो।','अनावश्यक हतारभन्दा तथ्य र तयारीलाई प्राथमिकता दिनुहोस्।','पुरानो काम पूरा गरेर नयाँ जिम्मेवारी लिनु उपयोगी हुनेछ।'],love:['सम्बन्धमा खुलेर कुरा गर्दा गलतफहमी घट्न सक्छ।','परिवार वा प्रिय व्यक्तिलाई समय दिनु राम्रो हुनेछ।','भावनात्मक प्रतिक्रिया दिनुअघि अर्को पक्षको कुरा सुन्नुहोस्।','सम्बन्धमा सानो सहयोगले सकारात्मक प्रभाव पार्न सक्छ।'],career:['काममा प्राथमिकता छुट्याएर अघि बढ्नुहोस्।','सहकर्मीसँग स्पष्ट समन्वयले समय बचाउन सक्छ।','नयाँ जिम्मेवारी आउन सक्छ; क्षमता अनुसार योजना बनाउनुहोस्।','अधुरो काम पूरा गरेपछि मात्र नयाँ काम थप्नु राम्रो हुनेछ।'],money:['आवश्यक र अनावश्यक खर्च छुट्याउनुहोस्।','ठूलो आर्थिक निर्णयमा तथ्य जाँच गरेर मात्र अघि बढ्नुहोस्।','बजेट मिलाएर चल्दा दबाब कम हुनेछ।','बचतलाई प्राथमिकता दिनु आज उपयोगी हुनेछ।'],health:['नियमित पानी, आराम र सन्तुलित खानामा ध्यान दिनुहोस्।','लामो समय एउटै ठाउँमा बस्नुपरे बीचमा विश्राम लिनुहोस्।','तनाव घटाउन पर्याप्त निद्रा र हल्का गतिविधि उपयोगी हुनेछ।','शरीरले दिएको संकेतलाई बेवास्ता नगर्नुहोस्।'],color:['रातो','हरियो','पहेंलो','सेतो','निलो','गुलाबी','बैजनी','सुन्तला'],number:['१','२','३','४','५','६','७','८','९']};
const seed=(d,i)=>{let h=2166136261;for(const c of `${d}:${i}`){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const pick=(a,s,i)=>a[seed(s,i)%a.length];
const forecast=(date,i)=>{const k=seed(date,i);return{overall:pick(p.overall,date,i),love:pick(p.love,date,i+11),career:pick(p.career,date,i+21),money:pick(p.money,date,i+31),health:pick(p.health,date,i+41),color:p.color[k%p.color.length],number:p.number[(k>>>8)%p.number.length],score:60+k%36}};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const load=async y=>(await fetch(`${BASE}data/calendar/${y}.json`,{cache:'no-store'})).json();
const findDay=async raw=>{const years=[2083,2084,2085];for(const y of years){try{const d=await load(y),x=d.days.find(a=>a.ad.date===raw);if(x)return x}catch(e){}}throw Error('आजको पात्रो डेटा भेटिएन।');};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const slides=document.getElementById('slides'),progress=document.getElementById('progress'),status=document.getElementById('status'),loading=document.getElementById('loading'),toast=document.getElementById('toast');
let index=0,locked=false,day=null,slideData=[];
function slideTemplate(i){const f=forecast(day.ad.date,i);return `<section class="slide"><article class="card sign-card"><div class="sign-icon">${signs[i][0]}</div><span class="eyebrow">आजको राशिफल · ${i+1}/12</span><h2 class="sign-name">${signs[i][1]}</h2><p class="sign-theme">${signs[i][2]}</p><p class="forecast">${esc(f.overall)}</p><div class="forecast-grid"><div class="forecast-box"><span>❤️ प्रेम</span><b>${esc(f.love)}</b></div><div class="forecast-box"><span>💼 करियर</span><b>${esc(f.career)}</b></div><div class="forecast-box"><span>💰 धन</span><b>${esc(f.money)}</b></div><div class="forecast-box"><span>🌿 स्वास्थ्य</span><b>${esc(f.health)}</b></div></div><div class="lucky"><span>शुभ रंग · <b>${f.color}</b></span><span>शुभ अंक · <b>${f.number}</b></span></div></article></section>`}
function render(){slides.innerHTML=`<section class="slide active"><article class="card hero-card"><div><span class="eyebrow">DAILY NEPALI ASTRO REEL</span><h1 class="hero-title">आजको<br>राशिफल</h1><p class="hero-sub">तपाईंको आजको दिन — एक नजरमा</p><div class="date-orbit"><div class="orb">☽</div><div><div class="date-big">${esc(day.bs.display)}</div><div class="date-ad">${esc(day.ad.date)} · ${esc(day.weekday?.nepali||'')}</div></div></div></div><p class="quote">दिनको सुरुवात स्पष्ट सोच, शान्त मन र सही प्राथमिकताबाट गरौं।</p></article></section><section class="slide"><article class="card tithi-card"><span class="eyebrow">आजको मिति</span><div class="date-big" style="font-size:36px;margin-top:10px">${esc(day.bs.display)}</div><div class="date-ad" style="font-size:12px;margin-top:8px">${esc(day.ad.date)} · ${esc(day.weekday?.nepali||'')}</div><div class="metric-grid"><div class="metric"><small>तिथि</small><b>${esc(day.tithi?.name||'—')}</b></div><div class="metric"><small>पक्ष</small><b>${esc(day.tithi?.paksha||'—')}</b></div><div class="metric"><small>नक्षत्र</small><b>${esc(day.nakshatra?.name||'—').split(' upto')[0]}</b></div><div class="metric"><small>राशि</small><b>${esc(day.rashi||'—').split(' upto')[0]}</b></div></div><div class="info-line"><span>सूर्योदय</span><b>${esc(day.sun?.sunrise||'—')}</b></div><div class="info-line"><span>पर्व / विशेष</span><b>${esc(day.festival||'सामान्य दिन')}</b></div></article></section><section class="slide"><article class="card tithi-card"><span class="eyebrow">आजको तिथि</span><div class="tithi-name">${esc(day.tithi?.name||'—')}</div><div class="paksha">${esc(day.tithi?.paksha||'')}</div><div class="metric-grid"><div class="metric"><small>अन्त्य समय</small><b>${esc(day.tithi?.end||'—')}</b></div><div class="metric"><small>पछि</small><b>${esc(day.tithi?.after||'—')}</b></div></div><p class="quote">आजको पञ्चाङ्ग विवरण नेपाली पात्रोको दैनिक डेटाबाट लिइएको हो।</p></article></section><section class="slide"><article class="card"><span class="eyebrow">१२ राशिहरू</span><h2 class="section-title">आजको दिनको संकेत</h2><div class="rashi-list">${signs.map((s,i)=>{const f=forecast(day.ad.date,i);return `<div class="rashi-row"><span class="rashi-symbol">${s[0]}</span><b class="rashi-name">${s[1]}</b><span class="rashi-text">${esc(f.overall)}</span></div>`}).join('')}</div></article></section>${signs.map((_,i)=>slideTemplate(i)).join('')}<section class="slide closing"><article class="card"><div class="closing-mark">✦</div><span class="eyebrow">आजको दिन</span><h2>शुभ रहोस् ✨</h2><p>तपाईंको आजको यात्रा शान्त, सकारात्मक र सफल रहोस्।</p><p class="eyebrow">LAXMAN · NEPALI RASHIFAL</p></article></section>`;slideData=[...slides.children];update(0,true)}
function update(next,initial=false){if(!slideData.length)return;index=Math.max(0,Math.min(slideData.length-1,next));slideData.forEach((s,i)=>{s.classList.remove('active','exit-up','exit-down');if(i===index)s.classList.add('active');else if(i<index)s.classList.add('exit-up');else s.classList.add('exit-down')});progress.style.setProperty('--p',`${((index+1)/slideData.length)*100}%`);status.textContent=index===0?'आजको नेपाली राशिफल':index===1?'आजको मिति':index===2?'आजको तिथि':index===3?'१२ राशिहरू':index<=15?`${signs[index-4]?.[1]||'राशिफल'} · ${index-3}/12`:'शुभ रहोस्';if(!initial)window.setTimeout(()=>{locked=false},430)}
function go(dir){if(locked)return;if(dir>0&&index===slideData.length-1){showToast('यो अन्तिम स्लाइड हो');return}if(dir<0&&index===0){showToast('सुरुवातको स्लाइड');return}locked=true;update(index+dir)}
function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),900)}
function key(e){if(['ArrowDown','PageDown','Enter',' '].includes(e.key)){e.preventDefault();go(1)}if(['ArrowUp','PageUp'].includes(e.key)){e.preventDefault();go(-1)}if(e.key==='Home'){e.preventDefault();update(0)}if(e.key==='End'){e.preventDefault();update(slideData.length-1)}}
let sy=0,sx=0,st=0;document.addEventListener('keydown',key);document.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)<12)return;go(e.deltaY>0?1:-1)},{passive:true});document.addEventListener('touchstart',e=>{const t=e.changedTouches[0];sx=t.clientX;sy=t.clientY;st=Date.now()},{passive:true});document.addEventListener('touchend',e=>{const t=e.changedTouches[0],dy=sy-t.clientY,dx=sx-t.clientX;if(Math.abs(dy)>45&&Math.abs(dy)>Math.abs(dx)*.8)go(dy>0?1:-1);else if(Date.now()-st<280&&Math.abs(dx)<25)go(1)},{passive:true});
(async()=>{try{day=await findDay(today());render();loading.classList.add('hide');setTimeout(()=>loading.remove(),700)}catch(e){loading.querySelector('span').textContent=e.message;loading.querySelector('.spinner').style.display='none'}})();
})();
